services:
  web:
    build: .
    container_name: comp7171-webapp
    ports:
      - "8000:8080"   # HTTP → localhost:8000
      - "8001:8081"   # HTTPS → localhost:8001
    volumes:
      - ./7071Group/auth.db:/app/auth.db
      - ./7071Group/care.db:/app/care.db
      - ./7071Group/housing.db:/app/housing.db
      - ./7071Group/hr.db:/app/hr.db
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=fateh
    restart: unless-stopped
