version: "3.8"

services:
  web:
    build: .
    container_name: comp7171-webapp
    ports:
      - "8000:8080"   # HTTP → localhost:8000
      - "8001:8081"   # HTTPS → localhost:8001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=fateh
    volumes:
      - ./7071Group/auth.db:/app/auth.db
      - ./7071Group/care.db:/app/care.db
      - ./7071Group/housing.db:/app/housing.db
      - ./7071Group/hr.db:/app/hr.db
      - ./aspnetapp.pfx:/https/aspnetapp.pfx:ro
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro 
