global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'aspnetcore'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:8001']
      - targets: ['192.168.50.194:8001']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
