apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comp7171-db-pvc
  namespace: default
  labels:
    app: comp7171-webapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
